### ISSUE TITLE
Static Assets

### ISSUE THREAD

**Issue by ErikSin** [digidem/react-native-with-mapeo-core-next#36]
### To Port Over
- [x] `images` folder
- [x] `animations` folder
- [x] `public` folder
- [x] `sharedComponents/icons` folder

**Comment by lightlii** [comment]
Just a quick clarification, `sharedComponents/icons` isn't static assets, it's a mixture of flow typed and ts files, some with external dependencies to install (`react-native-progress`). Do we still want to include these in the same PR? @ErikSin

**Comment by ErikSin** [comment]
> Just a quick clarification, `sharedComponents/icons` isn't static assets, it's a mixture of flow typed and ts files, some with external dependencies to install (`react-native-progress`, `react-native-vector-icons`). Do we still want to include these in the same PR? @ErikSin

Yes, I think we should still bring them over.
